<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatile" content="IE=edge">
    <meta name="viewport" content="width = device-width, initial-scale = 1">
    <title>Title</title>
    <link rel="stylesheet" href="/<?php echo ROOT;?>/bootstrap-4.3.1-dist/css/bootstrap.css" >
    <link rel="stylesheet" type="text/css" href="/<?php echo ROOT;?>/css/styles.css">

</head>
<body>

