<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatile" content="IE=edge">
    <meta name="viewport" content="width = device-width, initial-scale = 1">
    <title>Title</title>
    <link rel="stylesheet" href="/{{constant('ROOT')}}/bootstrap-4.3.1-dist/css/bootstrap.css" >
    <link rel="stylesheet" type="text/css" href="/{{constant('ROOT')}}/css/styles.css?<?php echo date('l jS \of F Y h:i:s A'); ?>">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
</head>
<body>

