<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {{HomeActive}}">
                <a class="nav-link" href="/{{constant('ROOT')}}/Home">Home</a>
            </li>


            {% if authorization == 0 %}
                <li class="nav-item {{SubmissionsActive}}">
                    <a class="nav-link" href="/{{constant('ROOT')}}/Submissions">My Submissions</a>
                </li>
                <li class="nav-item {{SubmitActive}}">
                    <a class="nav-link" href="/{{constant('ROOT')}}/Submit">Submit</a>
                </li>
            {% endif %}

            {% if authorization == 1 %}
                <li class="nav-item {{SubmissionsReviewActive}}">
                    <a class="nav-link" href="/{{constant('ROOT')}}/SubmissionsReview">Submissions to Reviews</a>
                </li>
            {% endif %}


            {% if authorization == 2 %}
            <li class="nav-item {{SetRightsActive}}">
                <a class="nav-link" href="/{{constant('ROOT')}}/SetRights">Set Rights</a>
            </li>

            <li class="nav-item {{AssignToReviewActive}}">
                <a class="nav-link" href="/{{constant('ROOT')}}/AssignToReview">Assign to Review</a>
            </li>
            {% endif %}
        </ul>

        {% if authorization >= 0 %}
        <ul class="navbar-nav">
            <li class="nav-item">
                <form action="/{{constant('ROOT')}}/Home/LogOut" method="post">
                    <input type="submit" class="nav-link btn btn-outline-light" id="logOutBtn" value="Log out">
                </form>
            </li>
        </ul>
        {% endif %}

        {% if authorization < 0 %}
        <ul class="navbar-nav">
            <li class="nav-item">
                <form action="/{{constant('ROOT')}}/SignIn" method="post">
                    <input type="submit" class="nav-link btn btn-outline-light" id="logInBtn" value="Sign in">
                </form>
            </li>
        </ul>
        {% endif %}
    </div>
</nav>