<div class="container">
    <div class="d-flex justify-content-center ">
        <div class="card">
            <div class="card-header">
                <h3>Register</h3>
            </div>
            <div class="card-body">
                <form action="/<?php echo ROOT;?>/Register/Register" method="post">
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"></span>
                        </div>
                        <input type="text" name="username" class="form-control" placeholder="username" >

                    </div>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"></i></span>
                        </div>
                        <input type="password" name="password" class="form-control" placeholder="password" >
                    </div>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"></i></span>
                        </div>
                        <input type="password" name="confirmpassword" class="form-control" placeholder="confirm password" >
                    </div>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"></span>
                        </div>
                        <input type="text" name="firstname" class="form-control" placeholder="first name" >
                    </div>

                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"></span>
                        </div>
                        <input type="email" name="email" class="form-control" placeholder="e-mail" >
                    </div>

                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"></span>
                        </div>
                        <input type="text" name="organization" class="form-control" placeholder="organization" >
                    </div>
                    <div class="form-group">
                        <input type="submit" name="register_btn" id="register_btn" value="Register" class="btn float-right">
                    </div>
                </form>
            </div>
            <div class="card-footer">
                <div class="links">
                    Already have an account?<a href="Signin.phtml">  Sign in</a>
                </div>
            </div>
        </div>
    </div>
</div>