<div class="container">
    <div class="d-flex justify-content-center ">
        <div class="card">
            <div class="card-header">
                <h3>Sign In</h3>
            </div>
            <div class="card-body">
                <form action="/{{constant('ROOT')}}/SignIn/SignIn" method="post">
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"></span>
                        </div>
                        <input type="text" name="username" class="form-control" placeholder="User name" value="{{lastInput.userName}}">

                    </div>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"></i></span>
                        </div>
                        <input type="password" name="password" class="form-control" placeholder="Password">
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Sign in" class="btn float-right confirmButton">
                    </div>
                </form>
            </div>


            {% if error is not empty %}
                <div class="alert alert-danger float-left w-100">{{ error[0] }}</div><br>
            {% endif %}

            <div class="card-footer">
                <div class="links">
                    Don't have an account?<a href="/{{constant('ROOT')}}/Register">  Register</a>
                </div>
            </div>
        </div>
    </div>
</div>