<div class="container">
    <div class="d-flex justify-content-center ">
        <div class="card">
            <div class="card-header">
                <h3>Sign In</h3>
            </div>
            <div class="card-body">
                <form action="Signin.phtml" method="post">
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"></span>
                        </div>
                        <input type="text" class="form-control" placeholder="username">

                    </div>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"></i></span>
                        </div>
                        <input type="password" class="form-control" placeholder="password">
                    </div>
                    <div class="form-group">
                        <input type="submit" id="login_btn" value="Login" class="btn float-right">
                    </div>
                </form>
            </div>
            <div class="card-footer">
                <div class="links">
                    Don't have an account?<a href="register.php">  Register</a>
                </div>
            </div>
        </div>
    </div>
</div>